### ISSUE TITLE
Live wind visualisation not showing particles

### ISSUE THREAD

**Issue by JackKelly** [philogb/philogb.github.com#1]
Hi Nicolas,

I'm a huge fan of your work!

I'm sorry to bring bad news but [the wind particle animation](http://philogb.github.io/page/wind/) on your site doesn't show the particles any more.  (At least, the particles don't show on my system running Firefox 75.0 on Ubuntu 19.10).

**Comment by philogb** [comment]
Thanks Jack - does [this version](https://deck.gl/showcases/wind/) work for you?

**Comment by JackKelly** [comment]
thanks so much for the very quick reply.

So, neither version works in Firefox for me (I've tested on both Ubuntu and MacOS; both using Firefox 75.0).

But both versions work really nicely in Chrome on MacOS for me :)    (Sorry, I should've tested another browser before posting!)

**Comment by philogb** [comment]
Sorry for the late reply here @JackKelly - I would recommend you to file a ticket on the [deck.gl](deck.gl) project as that's where the maintainers for the framework are and should be able to provide more help.

Thanks!
